export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USERS = 'UPDATE_USERS'
export const UPDATE_LANG = 'UPDATE_LANG'
export const SET_TRANSLATE_TERM = 'SET_TRANSLATE_TERM'
export const SET_DETECTED_LANG = 'SET_DETECTED_LANG'
export const UPDATE_RECIPIENT_USER = 'UPDATE_RECIPIENT_USER'
export const UPDATE_LIST = 'UPDATE_LIST'
export const UPDATE_LISTS = 'UPDATE_LISTS'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'
export const OPEN_CHAT = 'OPEN_CHAT'


export const UPDATE_CHAT = 'UPDATE_CHAT'
export const REMOVE_USER = 'REMOVE_USER'
