// export const API_ROOT = 'http://localhost:3001';
// export const API_WS_ROOT = 'ws://localhost:3001/cable';
export const API_ROOT = 'https://hello-world-rails-api.herokuapp.com';
export const API_WS_ROOT = 'wss://hello-world-rails-api.herokuapp.com/cable';

export const HEADERS = {
  'Content-Type': 'application/json',
  Accept: 'application/json'
};

export const googleLanguages = [
  {name: 'Arabic', code: 'ar'},
  {name: 'ChineseSimplified', code: 'zh-CN'},
  {name: "ChineseTraditional", code: 'zh-TW'},
  {name: 'Croatian', code: 'hr'},
  {name: 'Danish', code: 'da'},
  {name: 'Dutch', code: 'nl'},
  {name: 'English', code: 'en'},
  {name: 'Finnish', code: 'fi'},
  {name: 'French', code: 'fr'},
  {name: 'German', code: 'de'},
  {name: 'Greek', code: 'el'},
  {name: 'Hawaiian', code: 'haw'},
  {name: 'Hebrew', code: 'iw'},
  {name: 'Hindi', code: 'hi'},
  {name: 'Hungarian', code: 'hu'},
  {name: 'Icelandic', code: 'is'},
  {name: 'Indonesian', code: 'id'},
  {name: 'Irish', code: 'ga'},
  {name: 'Italian', code: 'it'},
  {name: 'Japanese', code: 'ja'},
  {name: 'Khmer', code: 'km'},
  {name: 'Korean', code: 'ko'},
  {name: 'Lao', code: 'lo'},
  {name: 'Latin', code: 'la'},
  {name: 'Malay', code: 'ms'},
  {name: 'Maori', code: 'mi'},
  {name: 'Mongolian', code: 'mn'},
  {name: 'Persian', code: 'fa'},
  {name: 'Polish', code: 'pl'},
  {name: 'Portuguese', code: 'pt'},
  {name: 'Punjabi', code: 'pa'},
  {name: 'Russian', code: 'ru'},
  {name: 'Slovak', code: 'sk'},
  {name: 'Spanish', code: 'es'},
  {name: 'Swahili', code: 'sw'},
  {name: 'Swedesh', code: 'sv'},
  {name: 'Tagolog', code: 'tl'},
  {name: 'Thai', code: 'th'},
  {name: 'Turkish', code: 'tr'},
  {name: 'Ukranian', code: 'uk'},
  {name: 'Vietnamese', code: 'vi'}
]

export const countries = [
  'Argentina',
  'Australia',
  'Austria',
  'Brazil',
  'Cambodia',
  'Canada',
  'Chile',
  'China',
  'Denmark',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Indonesia',
  'Italy',
  'Japna',
  'Malaysia',
  'Mexico',
  'Mongolia',
  'Morocoo',
  'Netherlands',
  'New Zealand',
  'Philippines',
  'Poland',
  'Portugal',
  'Russia',
  'Singapore',
  'South Korea',
  'Spain',
  'Sweden',
  'Thailand',
  'United Kingdom',
  'United States of America',
  'Vietnam'
]
